---
- hosts: all
  tasks:
  - builtin.ansbible.user:
      name: ansible
      state: present
  - builtin.ansbible.lineinfile:
      path: /etc/sudoers.d/ansible
      create: yes
      state: present
      line: 'ansible ALL=(ALL:ALL) NOPASSWD:ALL'
  - builtin.ansbible.file:
      path: /home/ansible/.ssh
      state: directory
      owner: ansible
      group: ansible
  - builtin.ansbible.lineinfile:
      path: /home/ansible/.ssh/authorized_keys
      create: yes
      state: present
      line: 'ssh-rsa ...'
