---
- name: install cluster
  hosts: all
  become: yes
  roles: 
    - etcd
    - patroni
    - bouncer

# Для реализации паузы между запусками нод кластера пришлось вынести запуск в отдельую роль и выполнять последовательно. 
- name: run cluster
  hosts: all
  become: yes
  gather_facts: no
  serial: 1
  roles:
    - run